### ISSUE TITLE
`BuilderConstants` failure with Android Studio 0.6, Android Gradle plugin v11

### ISSUE THREAD

**Issue by raycohen** [JakeWharton/hugo#32]
After upgrading Android Studio to 0.6.0, I get the following error when gradle syncs:

```
java.lang.NoClassDefFoundError: com.android.builder.BuilderConstants
at hugo.weaving.plugin.HugoPlugin$_apply_closure2.class$(HugoPlugin.groovy)
at hugo.weaving.plugin.HugoPlugin$_apply_closure2.$get$$class$com$android$builder$BuilderConstants(HugoPlugin.groovy)
at hugo.weaving.plugin.HugoPlugin$_apply_closure2.doCall(HugoPlugin.groovy:35)
at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:58)
```

If I comment out `apply plugin: 'hugo'` the error goes away

Android Studio 0.6 also made me update buildToolsVersion to 19.1.0
